parameters:
#    tiku_questions.example.class: Tiku\QuestionsBundle\Example

services:
#    tiku_questions.example:
#        class: %tiku_questions.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
